config/routes.rb
Gitchat::Application.routes.draw do
  get "message/index"

  resources :rooms
  resources :login
  resources :logout

  root :to => 'rooms#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible :created_at, :del_flg, :deleted_at, :max_head_count, :name, :updated_at, :version
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :check_logined

  def initialize
    super
    @github_login_url = URI::HTTPS.build({
      :host => Settings.github.host,
      :path => Settings.github.auth_path,
      :query => [
        [
          'client_id', Settings.github.client_id
        ].join('='),
      ].join('&'),
    }).to_s
  end

  private
  def check_logined
    if session[:access_token] then
      client = Octokit::Client.new(:login => "me",  :oauth_token => session[:access_token])
      @user = client.user
    end
  end
end

app/controllers/login_controller.rb
# coding: utf-8
require 'net/https'
include LoginHelper

class LoginController < ApplicationController

  # GET /login
  # GET /login.json
  def index
    # redirect from /login/oauth/authorize
    if request.get?
      code = params[:code].to_s
      if code.empty?
        respond_to do |format|
          format.html { redirect_to '/' }
        end
      end

      ###
      # access_token を取得するため，postリクエストする
      ###
      request = Net::HTTP::Post.new(
        Settings.github.access_token_path,
        {'Content-Type' =>'application/json'}, # initheader
      )
      request.body = {
        :client_id     => Settings.github.client_id,
        :client_secret => Settings.github.client_secret,
        :code          => code,
      }.to_json

      http = Net::HTTP.new(Settings.github.host, '443')
      http.use_ssl = true

      # 証明書を使わない
      http.verify_mode = OpenSSL::SSL::VERIFY_NONE

      # for debug
      http.set_debug_output $stderr

      response = nil
      http.start do |h|
        response = h.request(request)
      end

      body = parse_response_body(response.body)
      if body['access_token']
        session[:access_token] = body['access_token']
      end

      respond_to do |format|
        format.html { redirect_to '/' }
      end

    # get 以外の場合はエラー
    else
      respond_to do |format|
        format.html { redirect_to '/' }
      end
    end
  end
end

app/controllers/logout_controller.rb
class LogoutController < ApplicationController
  def index
    reset_session
    redirect_to '/'
  end
end

app/controllers/members_controller.rb
# coding: utf-8
class MembersController < ApplicationController
  def add
    @partial_message = {
      :partial => 'members',
      :room_id  => params[:room_id].to_s
    }
    respond_to do |format|
      format.js {render :layout => false} # create.js.erb
    end
  end
end

app/controllers/message_controller.rb
# coding: utf-8
class MessageController < ApplicationController
  def create
    @partial_message = {
      :partial => 'message',
      :object  => [params[:room_id].to_s, params[:message].to_s]
    }
    respond_to do |format|
      format.js {render :layout => false} # create.js.erb
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rooms }
    end
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @room = Room.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/new
  # GET /rooms/new.json
  def new
    @room = Room.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(params[:room])

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render json: @room, status: :created, location: @room }
      else
        format.html { render action: "new" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rooms/1
  # PUT /rooms/1.json
  def update
    @room = Room.find(params[:id])

    respond_to do |format|
      if @room.update_attributes(params[:room])
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room = Room.find(params[:id])
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper

  def parse_response_body target_str
    pattern = '([^=]*)=([^&]*)'
    p = target_str.match(/#{pattern}/)
    return {p[1] => p[2]}
  end
end

app/helpers/logout_helper.rb
module LogoutHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "GitChat" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>


    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="brand" href="/">GitChat</a>
          <div class="container-fluid">
            <ul class="nav">
              <% if session[:access_token] then %>
                <li><%= link_to "LOGOUT", '/logout' %></li>
              <% else %>
                <li><%= link_to "LOGIN", @github_login_url %></li>
              <% end %>
              <% if @user then %>
              </ul>
              <ul class="nav pull-right">
                <li>
                <%= link_to image_tag(@user.avatar_url, :id => 'nav_icon') + ' ' + @user.login,
                  "https://github.com/#{@user.login}" %>
                </li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
      <footer class="pull-right">
        <p>&copy; 2013 GitChat. All rights reserved.</p>
        <p><%= link_to 'hamaan29(github)', 'https://github.com/hamaan29' %> / <%= link_to '@haman29', 'https://twitter.com/haman29' %></p>
      </footer>
    </div> <!-- /container -->
  </body>
</html>

app/views/login/index.html.erb
<h1>login complete</h1>
<%= 'your access token: ' + @session[:access_token] %>

app/views/members/_members.html.erb
<tr>
  <td><%= link_to image_tag(@user.avatar_url), "https://github.com/#{@user.login}" %></td>
</tr>

app/views/members/add.js.erb
<% publish_to "/rooms/#{@partial_message[:room_id]}" do %>
  $('#members_count').text(parseInt($('#members_count').text()) + 1);
  $('#members').prepend("<%= j render(@partial_message) %>");
<% end %>

app/views/message/_message.html.erb
<tr>
  <td>
    <%= @user.login %><br />
    <%= link_to image_tag(@user.avatar_url), "https://github.com/#{@user.login}" %>
  </td>
  <td><%= @partial_message[:object][1] %></td>
</tr>

app/views/message/create.js.erb
<% publish_to "/rooms/#{@partial_message[:object][0]}" do %>
  $("#chat_text_box").val('');
  $("#chat").prepend("<%= j render(@partial_message) %>");
<% end %>

app/views/rooms/_form.html.erb
<%= form_for @room, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                rooms_path, :class => 'btn' %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<%- model_class = Room -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/rooms/index.html.erb
<%- model_class = Room -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <% if session[:access_token] then %>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= link_to room.name, room_path(room) %></td>
        <% if session[:access_token] then %>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_room_path(room), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        room_path(room),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-mini btn-danger' %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if session[:access_token] then %>
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_room_path,
              :class => 'btn btn-primary' %>
<% end %>

app/views/rooms/new.html.erb
<%- model_class = Room -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/rooms/show.html.erb
<%- model_class = Room -%>
<div class="page-header">
  <h1><%=t '.title', :default => @room.name %></h1>
</div>
<%= subscribe_to "/rooms/#{@room.id}" %>
<%= form_tag({:controller => 'message',  :action => 'create.js'},  :remote => true) do %>
  <%= text_field_tag(:message,  '',  {:id => 'chat_text_box'}) %>
  <%= hidden_field_tag 'room_id',  @room.id %>
  <%= submit_tag 'POST' %>
<% end %>
<table id="chat" class="common-table table-striped table-condensed">
</table>